server:
  port: 8081

spring:
  application:
    name: conversion-service
  profiles:
    active: dev
  # tells the app to gets its settings from our config server
  config:
    import: "optional:configserver:http://localhost:8888"

# enable actuator endpoints so we can refresh settings dynamically
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"

spring.cloud.openfeign.client.config:
  partner-rate-service:
    connectTimeout: 1000
    readTimeout: 1500

resilience4j.circuitbreaker:
  instances:
    partnerServiceBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      ignoreExceptions:
        - com.tcs.conversionservice.exception.CurrencyNotSupportedException

resilience4j.retry:
  instances:
    partnerServiceRetry:
      maxAttempts: 3
      waitDuration: 2s  # Waits 2 seconds between retries
      ignoreExceptions:
        - com.tcs.conversionservice.exception.CurrencyNotSupportedException # not retry 404